### ISSUE TITLE
Some Imgur GIFs not displaying

### ISSUE THREAD

**Issue by Ludophonic** [Ludophonic/NeoGFY#6]
There should be two GIFs in [this post](http://www.neogaf.com/forum/showpost.php?p=216492082&postcount=3315), only the first shows up.

GIF in [this post](http://www.neogaf.com/forum/showpost.php?p=216390651&postcount=234) does not show up.

**Comment by Ludophonic** [comment]
For the first GIF the URL has ?nodirect appended to the end (http://i.imgur.com/QS58D.gif?noredirect).

The second GIF does not seem to have an mp4 version.

**Comment by Uhyve** [comment]
In background.js, if you change your filter to `"*://*.imgur.com/*.gif*"`, then change how you block the GIFs to something like:

```
p = info.url.search( "imgur.com/" );
if( p >= 0 )
{
	var schemepos = image.src.search("://");
	var scheme = image.src.substring(0, schemepos);
	var extpos = info.url.lastIndexOf( ".gif" );
	var uniquename = info.url.substring( p+10, extpos );
	newurl = scheme + "://i.imgur.com/" + uniquename + "h.jpg"; // h suffix for 'huge' thumbnail
}
```

Then in inject.js replace the start of your imgur rewrite code with something like this.
```
rewrite = image.src.match( "imgur.com/.*(.gif(.*))$" );
if( rewrite )
{
	var p = image.src.search( "imgur.com/" );
	if( p >= 0 )
 	{
   		var extpos = image.src.lastIndexOf( ".gif" );
   		var uniquename = image.src.substring( p + 10, extpos );
 		//console.log( "found '" + uniquename + "' @ " + image.src );

 		var schemepos = image.src.search( "://" );
  		var scheme = image.src.substring( 0, schemepos );
```

Also I think you'd have to change your manifest to catch "www.imgur.com". Just made myself a quick version of this for another site, so I was messing with the code alittle, dunno if that helps you any. But it got both of the examples working for me.

Oh, and I dunno if this is specific to the site I was messing with but with some larger imgur GIFs, they were getting caught by the `if (image.naturalHeight <= 64)` line, naturalHeight was returning 0 (I guess they hadn't loaded yet), so I added a `&& image.naturalHeight != 0` which fixed it for me.

**Comment by Ludophonic** [comment]
Yeah, I'll need change the regex.

As for larger gifs getting caught when naturalHeight returns 0 that is deliberate. I'm being conservative there but and argument can be made for either behaviour. Ideally I should defer until the poster image has loaded and I can get the size to make the decision.

**Comment by Uhyve** [comment]
Ah I see, yeah, it'd make alot of sense for it to decide after figuring out the height of the GIF. 

Unrelated: While I'm here, I should thank you, very polished extension, super cool that you've used a really open licence. Tons of respect for that. Also, I've never done any web code stuff before (you could probably tell, heh), but your code is super readable.

**Comment by Ludophonic** [comment]
A couple of the GIFs in [this post](http://www.neogaf.com/forum/showthread.php?t=1326960) don't play while all the others do. Imgur seems to have not created mp4 versions. There is no difference in URL scheme from the ones that do and don't work.

**Comment by Ludophonic** [comment]
[New \<video\> Policies for iOS](https://webkit.org/blog/6784/new-video-policies-for-ios/) has some useful advice for fallback when video is not present.

**Comment by Ludophonic** [comment]
For the second missing GIF from the first comment (the one in [this post](http://www.neogaf.com/forum/showpost.php?p=216390651&postcount=234)) what seems to be happening is that Imgur is redirecting http://www.imgur.com/GFDHXXb.gif to http://imgur.com/GFDHXXb.gif
This causes the blocking code to intercept it, but it then does not get rewritten within the page because the IMG element within the webpage still has www.imgur.com in its src property.

**Comment by Ludophonic** [comment]
All the examples within now display.

**Comment by Ludophonic** [comment]
Imgur fallback not working for some GIFs in [this post](http://www.neogaf.com/forum/showpost.php?p=228236127&postcount=134)

**Comment by Ludophonic** [comment]
Imgur loading poster but not replacing with mp4 in [this post](http://www.neogaf.com/forum/showpost.php?p=238074156&postcount=2) - Safari version just gives a broken image. There are also a couple other GIFs in the same thread not correctly replaced.

**Comment by Ludophonic** [comment]
Safari given broken image on [this post](http://www.neogaf.com/forum/showpost.php?p=241466289&postcount=234)

**Comment by Ludophonic** [comment]
Not Imgur, but [this post](http://www.neogaf.com/forum/showpost.php?p=241660620&postcount=1623) has a [giphy gif](https://i.giphy.com/media/v19zPq7Zm9EBO/giphy.gif) that is not working. Blocked but not replaced on Safari.

**Comment by Ludophonic** [comment]
Above GIFs now working properly.
